name: Teste da Aplicação DjangoChopp
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'  

    - name: Instalar dependências do Python
      run: |
        pip install -r requirements.txt
      working-directory: /teste  

    - name: Executar Testes Django
      run: |
        python manage.py test
      working-directory: /teste # Substitua pelo caminho do seu projeto Django
